# Generated by Django 2.1.1 on 2018-09-07 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_purchase_avrg_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='nome',
        ),
    ]
