# Generated by Django 2.1.1 on 2018-09-07 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_auto_20180907_1228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='avrg_price',
            new_name='preco_medio',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='total_price',
            new_name='preco_total',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='product',
            new_name='produto',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='amount',
            new_name='quantidade',
        ),
    ]
