# Generated by Django 2.1.1 on 2018-09-07 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_auto_20180907_1231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='nome',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='quantidade',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='preco_medio',
            new_name='avrg_price',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='produto',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='preco_total',
            new_name='total_price',
        ),
    ]
